const { app, BrowserWindow } = require('electron')
const path = require('path')
app.disableHardwareAcceleration()
app.commandLine.appendSwitch('no-sandbox')
app.commandLine.appendSwitch('disable-gpu')
setTimeout(() => { console.error('timeout'); app.exit(1) }, 30000)
app.whenReady().then(async () => {
  const win = new BrowserWindow({ show: false, width: 900, height: 1100 })
  await win.loadFile(path.join(__dirname, 'variants.html'))
  await new Promise(r => setTimeout(r, 400))
  const img = await win.webContents.capturePage()
  require('fs').writeFileSync(path.join(__dirname, 'sheet.png'), img.toPNG())
  console.log('sheet.png saved')
  app.exit(0)
})
